In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn import linear_model as lm

In [3]:
x_1 = np.random.uniform(10,40,100)
x_2 = np.random.uniform(-50,20,100)
x_3 = np.random.uniform(20,60,100)
x_4 = np.random.uniform(10,40,100)
x_5 = np.random.uniform(-50,20,100)
x_6 = np.random.uniform(20,60,100)
epsilon = np.random.normal(0,10,100)

In [4]:
y=-30+1.3*x_1+1.6*x_2+1.1*x_3+0.7*x_4-2.1*x_5-0.9*x_6+epsilon

In [5]:
X_ols=pd.DataFrame()
X_ols['Constant']=pd.Series(np.ones(100))
X_ols['X1'] = pd.Series(x_1)
X_ols['X2'] = pd.Series(x_2)
X_ols['X3'] = pd.Series(x_3)
X_ols['X4'] = pd.Series(x_4)
X_ols['X5'] = pd.Series(x_5)
X_ols['X6'] = pd.Series(x_6)

In [14]:
X_ols

Constant         X1         X2         X3         X4         X5         X6
0        1.0  24.339952   9.404506  36.428060  33.173479   2.738200  55.689090
1        1.0  27.605230 -43.198514  37.924435  29.333109 -45.210609  32.859447
2        1.0  23.773170   2.412406  57.345802  27.003203  13.819585  49.781253
3        1.0  36.310290 -31.989534  44.566794  19.441320  -4.321395  28.207045
4        1.0  30.400380  14.709055  57.486337  26.250724  -4.654251  43.479979
..       ...        ...        ...        ...        ...        ...        ...
95       1.0  23.521726  14.554785  50.385661  24.797544   5.284829  46.163251
96       1.0  18.982790  10.831754  49.031219  30.868406 -27.670605  59.609837
97       1.0  21.938994  17.552925  54.699428  39.760293 -17.138872  53.664671
98       1.0  18.004619 -27.464074  30.597029  26.643260  -6.262645  20.654345
99       1.0  36.778235 -34.199933  46.922506  39.252943  -9.340685  54.373761

[100 rows x 7 columns]

In [6]:
model_reg = sm.OLS(y,X_ols).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.968
Model:                            OLS   Adj. R-squared:                  0.966
Method:                 Least Squares   F-statistic:                     475.7
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           1.74e-67
Time:                        19:45:28   Log-Likelihood:                -369.42
No. Observations:                 100   AIC:                             752.8
Df Residuals:                      93   BIC:                             771.1
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -36.1280      6.289     -5.745      0.000     -48.616     -23.640
X1             1.4641      0.118     12.403      0.000       1.230       1.698
X2             1.5540      0.049     31.759      0.000       1.457       1.651
X3             0.9254      0.092     10.029      0.000       0.742       1.109
X4             0.7387      0.118      6.245      0.000       0.504       0.974
X5            -2.2223      0.054    -41.470      0.000      -2.329      -2.116
X6            -0.7932      0.089     -8.926      0.000      -0.970      -0.617
==============================================================================
Omnibus:                        2.822   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.244   Jarque-Bera (JB):                2.587
Skew:                          -0.310   Prob(JB):                        0.274
Kurtosis:                       2.513   Cond. No.                         442.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [7]:
# Now we add some unrelated coefficients
x_7 = np.random.uniform(10,40,100)
x_8 = np.random.uniform(-50,20,100)
x_9 = np.random.uniform(20,60,100)
x_10 = np.random.uniform(10,40,100)
x_11 = np.random.uniform(-50,20,100)
x_12 = np.random.uniform(20,60,100)

In [8]:
X_ext = pd.DataFrame()
X_ext['Constant']=pd.Series(np.ones(100))
X_ext['X1'] = pd.Series(x_1)
X_ext['X2'] = pd.Series(x_2)
X_ext['X3'] = pd.Series(x_3)
X_ext['X4'] = pd.Series(x_4)
X_ext['X5'] = pd.Series(x_5)
X_ext['X6'] = pd.Series(x_6)
X_ext['X7'] = pd.Series(x_7)
X_ext['X8'] = pd.Series(x_8)
X_ext['X9'] = pd.Series(x_9)
X_ext['X10'] = pd.Series(x_10)
X_ext['X11'] = pd.Series(x_11)
X_ext['X12'] = pd.Series(x_12)

In [9]:
model_reg = sm.OLS(y,X_ext).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.969
Model:                            OLS   Adj. R-squared:                  0.965
Method:                 Least Squares   F-statistic:                     226.4
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           3.80e-60
Time:                        19:45:28   Log-Likelihood:                -368.58
No. Observations:                 100   AIC:                             763.2
Df Residuals:                      87   BIC:                             797.0
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -32.4202     10.004     -3.241      0.002     -52.304     -12.536
X1             1.4775      0.127     11.673      0.000       1.226       1.729
X2             1.5521      0.052     30.096      0.000       1.450       1.655
X3             0.9308      0.096      9.663      0.000       0.739       1.122
X4             0.7390      0.122      6.033      0.000       0.495       0.982
X5            -2.2238      0.057    -38.777      0.000      -2.338      -2.110
X6            -0.7888      0.094     -8.406      0.000      -0.975      -0.602
X7            -0.0555      0.130     -0.426      0.671      -0.314       0.203
X8             0.0531      0.054      0.981      0.329      -0.054       0.161
X9            -0.0326      0.086     -0.378      0.706      -0.204       0.139
X10            0.0018      0.135      0.013      0.989      -0.266       0.270
X11            0.0306      0.053      0.583      0.561      -0.074       0.135
X12           -0.0133      0.095     -0.139      0.889      -0.203       0.176
==============================================================================
Omnibus:                        2.317   Durbin-Watson:                   1.936
Prob(Omnibus):                  0.314   Jarque-Bera (JB):                1.993
Skew:                          -0.226   Prob(JB):                        0.369
Kurtosis:                       2.476   Cond. No.                         974.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [10]:
# When we input the matrix, we don't need to add the column of ones because \
# Lasso automatically takes it into account

X_ext = X_ext.drop(columns=['Constant'])
model_lasso = lm.Lasso(alpha=1).fit(X_ext,y)
model_lasso.coef_

array([ 1.46294307,  1.55027828,  0.92284962,  0.72644038, -2.22015979,
       -0.78062871, -0.03711098,  0.04799422, -0.02560489,  0.        ,
        0.02732307, -0.0032985 ])

In [16]:
model_lasso = lm.Lasso(alpha=5).fit(X_ext,y)
model_lasso.coef_

array([ 1.39738349,  1.54149457,  0.89646171,  0.67030692, -2.20731056,
       -0.74711898, -0.        ,  0.03143473, -0.        ,  0.        ,
        0.01554568, -0.        ])

In [11]:
model_lasso = lm.Lasso(alpha=10).fit(X_ext,y)
model_lasso.coef_

array([ 1.31193289,  1.53269589,  0.86332346,  0.59803113, -2.18922902,
       -0.70753584, -0.        ,  0.01449956, -0.        ,  0.        ,
        0.        , -0.        ])

In [18]:
model_lasso = lm.Lasso(alpha=20).fit(X_ext,y)
model_lasso.coef_

array([ 1.1530718 ,  1.51231571,  0.80024469,  0.45338826, -2.15485581,
       -0.62647681, -0.        ,  0.        , -0.        ,  0.        ,
        0.        , -0.        ])

In [17]:
model_lasso = lm.Lasso(alpha=100).fit(X_ext,y)
model_lasso.coef_

array([ 0.        ,  1.32876979,  0.2343748 ,  0.        , -1.88329575,
       -0.        , -0.        , -0.        , -0.        ,  0.        ,
       -0.        , -0.        ])

In [12]:
# We now apply Ridge Regression to our data

model_ridge = lm.Ridge(alpha=10).fit(X_ext,y)
model_ridge.coef_

array([ 1.47496611,  1.55175844,  0.93025542,  0.73783167, -2.22302065,
       -0.78823707, -0.05543317,  0.0529459 , -0.03268604,  0.00264594,
        0.0305383 , -0.01332888])

In [13]:
model_ridge = lm.Ridge(alpha=10000).fit(X_ext,y)
model_ridge.coef_

array([ 0.53640173,  1.23518998,  0.55049338,  0.31322488, -1.67344044,
       -0.48608879, -0.01154473,  0.00681034, -0.06172446,  0.14568318,
       -0.00304285, -0.00223446])